In [1]:
import tensorflow as tf


D:\SOFTWARES DATA SCIENCE\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\SOFTWARES DATA SCIENCE\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\SOFTWARES DATA SCIENCE\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\SOFTWARES DATA SCIENCE\An

In [2]:
print(tf.__version__)

1.14.0


In [215]:
h = tf.constant('Hello ')
w = tf.constant('World!')
hww=h+h
hw = h+w
with tf.Session() as sess:
    ans=sess.run(hw)
    ans2=sess.run(hww)
print(ans)
print(ans2)
print(hw)

b'Hello World!'
b'Hello Hello '
Tensor("add_6:0", shape=(), dtype=string)


## Softmax program

In [8]:
from tensorflow.examples.tutorials.mnist import input_data

DATA_DIR = '/tmp/data'
NUM_STEPS = 1000
MINIBATCH_SIZE = 100

In [32]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [9]:
data = input_data.read_data_sets(DATA_DIR, one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from t

In [77]:
x=tf.placeholder(shape=[None,784],name='first_var',dtype=tf.float32)
w=tf.Variable(tf.zeros([784,10]),name='var2')

In [80]:
y_true = tf.placeholder(tf.float32, [None, 10])
y_pred = tf.matmul(x, w)

In [87]:
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y_pred,labels=y_true))

gd_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

correct_mask = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))
accuracy = tf.reduce_mean(tf.cast(correct_mask, tf.float32))

In [90]:
with tf.Session() as sess:

    # Train
    sess.run(tf.global_variables_initializer())
    for _ in range(NUM_STEPS):
        batch_xs, batch_ys = data.train.next_batch(MINIBATCH_SIZE)
        sess.run(gd_step, feed_dict={x: batch_xs, y_true: batch_ys})

    # Test
    ans = sess.run(accuracy, feed_dict={x: data.test.images, y_true: data.test.labels})

print("Accuracy: {:.4}%".format(ans*100))

Accuracy: 91.91%


## Tensorflow Basics

In [109]:
a = tf.constant(5)
b = tf.constant(8)
ab = tf.multiply(a,b)

In [111]:
with tf.Session() as sess:
    ans=sess.run(ab)
print(ans)

40


In [114]:
sess = tf.Session()
outs = sess.run(ab)
sess.close()
print('the product a by b = {}'.format(outs))

the product a by b = 40


### constructing and managing graphs

In [216]:
print(tf.compat.v1.get_default_graph)

<function get_default_graph at 0x00000195818239D8>


In [128]:
g = tf.Graph()
print(g)

In [138]:
#we can view the graph it’s associated with by using the <node>.graph attribute:
print(a.graph is g)
print(a.graph is tf.get_default_graph())

False
True


In [140]:
g1 = tf.get_default_graph()
g2 = tf.Graph()
print(g1 is tf.get_default_graph())
with g2.as_default():
    print(g1 is tf.get_default_graph())
print(g1 is tf.get_default_graph())

True
False
True


### Data Types

In [150]:
c = tf.constant(4.0 , dtype=tf.float32,name='cc')
c1 = tf.constant(5.0, dtype=tf.float32,name='cc')

In [155]:
print(c)
print(c1)
print(c.dtype)
print(c1.name)
print(c.get_shape())

Tensor("cc_4:0", shape=(), dtype=float32)
Tensor("cc_5:0", shape=(), dtype=float32)
<dtype: 'float32'>
cc_5:0
()


In [214]:
print(c.ndim)

AttributeError: 'Tensor' object has no attribute 'ndim'

### casing

In [157]:
x = tf.constant([1,2,3],name='x',dtype=tf.float32)
print(x.dtype)
x = tf.cast(x,tf.int64)
print(x.dtype)

<dtype: 'float32'>
<dtype: 'int64'>


In [158]:
aa=x+3

In [162]:
with tf.Session() as sess:
    ans=sess.run(aa)
print(ans)

[4 5 6]


In [165]:
print(ans.dtype)

int64


### shapes

In [167]:
import numpy as np
c = tf.constant([[1,2,3],[4,5,6]])

print("Python List input: {}".format(c.get_shape()))
c = tf.constant(np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]]))

print("3d NumPy array input: {}".format(c.get_shape()))

Python List input: (2, 3)
3d NumPy array input: (2, 2, 3)


### interactive session

In [217]:
# A feature that is convenient to use when we want to explore the data content of an object

sess = tf.compat.v1.InteractiveSession()
c = tf.linspace(0.0, 4.0, 5)
print("The content of 'c':\n {}\n".format(c.eval()))
sess.close()

The content of 'c':
 [0. 1. 2. 3. 4.]



In [207]:
a = tf.constant([[1,2,3],[4,5,6]])
print(a.get_shape())
x = tf.constant([1,0,1])
print(x.get_shape())

(2, 3)
(3,)


In [208]:
x = tf.expand_dims(x,1)

In [209]:
x

<tf.Tensor 'ExpandDims_13:0' shape=(3, 1) dtype=int32>

In [210]:
sess = tf.InteractiveSession()
xx=x
print("The content of 'c':\n {}\n".format(x.eval()))
sess.close()

The content of 'c':
 [[1]
 [0]
 [1]]



## Variables